(test
 (name test_view)
 (modules test_view gen_view)
 (libraries view alcotest qcheck qcheck-alcotest))

(test
 (name test_kernel)
 (modules test_kernel gen_view)
 (libraries kernel ast view alcotest qcheck qcheck-alcotest))

(test
 (name test_eval)
 (modules test_eval)
 (libraries ast view alcotest))

(test
 (name test_expand)
 (modules test_expand)
 (libraries transform ast view alcotest))

(test
 (name test_jvp)
 (modules test_jvp)
 (libraries transform ast view alcotest))

(test
 (name test_forward)
 (modules test_forward)
 (libraries transform ast view alcotest))

(test
 (name test_unzip)
 (modules test_unzip)
 (libraries transform ast view alcotest))

(test
 (name test_transpose)
 (modules test_transpose)
 (libraries transform ast view alcotest))

(test
 (name test_viewspec)
 (modules test_viewspec)
 (libraries transform ast view alcotest))

(test
 (name test_desugar)
 (modules test_desugar)
 (libraries transform ast view alcotest))

(test
 (name test_linreg)
 (modules test_linreg)
 (libraries transform ast view alcotest))

(test
 (name test_perf)
 (modules test_perf)
 (libraries transform ast view blas_stub alcotest))

(test
 (name test_threefry)
 (modules test_threefry)
 (libraries prng alcotest))

(test
 (name test_prob)
 (modules test_prob)
 (libraries ast prng alcotest))

(executable
 (name test_coverage)
 (modules test_coverage gen_view)
 (libraries view qcheck))
