type loc = { file : string; line : int; col : int }

let dummy_loc = { file = "<none>"; line = 0; col = 0 }

(* --- viewspec: logical description of affine index maps --- *)

type viewop =
  | Vtranspose of int array              (* axis permutation *)
  | Vslice of (int * int * int) array    (* start, stop, step per axis *)
  | Vbroadcast of int * int              (* axis, size *)
  | Vreshape of int array                (* target shape *)

type viewspec = viewop list              (* applied left-to-right *)

type prim =
  (* map1 *)
  | Neg | Exp | Log | Logsigmoid | Sqrt | Relu | Step | Erf | Erfinv
  (* map2 — require shape match *)
  | Add | Sub | Mul | Div | Max2
  (* reduce *)
  | Sum_axis of int | Max_axis of int
  (* structural *)
  | Gather of int * int array (* axis, indices — integer, no tangent (§3.1) *)
  (* reduce — argmax *)
  | Argmax_axis of int        (* like Max_axis but returns argmax as float *)
  (* select by dynamic index tensor *)
  | Select_axis of int        (* axis; second arg is index tensor (int-valued float) *)
  (* adjoint ops (generated by transpose) *)
  | Scatter_add of int * int array * int array        (* axis, indices, target_shape *)
  | Scatter_select_add of int * int                   (* axis, target_axis_size *)
  (* viewspec-based structural ops *)
  | Apply_view of viewspec               (* σ*: pullback (read through view) *)
  | Adjoint_view of viewspec * int array (* σ_*: pushforward; int array = target shape *)
  (* linear algebra *)
  | Matmul

type expr =
  | Const  of loc * value
  | Var    of loc * string
  | Prim   of loc * prim * expr list
  | Let    of loc * string * expr * expr
  | Rank   of loc * int * prim * expr list
  | Sample of loc * string * int array * dist
  | Score  of loc * expr

and value = View.Tensor.t   (* future: variant with dtype *)

and dist =
  | D_uniform
  | D_categorical of expr
  | D_pushforward of {
      fwd_var : string; fwd : expr;
      inv_var : string; inv : expr;
      base : dist;
    }
  | D_product of dist * dist

let loc_of = function
  | Const (l, _) | Var (l, _) | Prim (l, _, _) | Let (l, _, _, _)
  | Rank (l, _, _, _) | Sample (l, _, _, _) | Score (l, _) -> l

(* --- constructors with dummy_loc for tests --- *)

let const v       = Const (dummy_loc, v)
let var s         = Var (dummy_loc, s)
let prim p args   = Prim (dummy_loc, p, args)
let let_ s e body = Let (dummy_loc, s, e, body)
let rank k p args  = Rank (dummy_loc, k, p, args)
let sample name frame dist = Sample (dummy_loc, name, frame, dist)
let score e = Score (dummy_loc, e)

(* --- viewspec shape computation --- *)

let viewop_output_shape (op : viewop) (in_shape : int array) : int array =
  match op with
  | Vtranspose p -> Array.init (Array.length p) (fun i -> in_shape.(p.(i)))
  | Vslice r ->
    Array.init (Array.length in_shape) (fun k ->
      let (start, stop, step) = r.(k) in
      if step > 0 then (stop - start + step - 1) / step
      else (start - stop + (-step) - 1) / (-step))
  | Vbroadcast (a, sz) ->
    let r = Array.length in_shape in
    Array.init (r + 1) (fun i ->
      if i < a then in_shape.(i) else if i = a then sz else in_shape.(i - 1))
  | Vreshape s -> s

let viewspec_output_shape (spec : viewspec) (in_shape : int array) : int array =
  List.fold_left (fun sh op -> viewop_output_shape op sh) in_shape spec

(* Compute all intermediate shapes: shapes.(0) = in_shape, shapes.(i+1) = after op i *)
let viewspec_intermediate_shapes (spec : viewspec) (in_shape : int array)
    : int array array =
  let n = List.length spec in
  let shapes = Array.make (n + 1) in_shape in
  List.iteri (fun i op ->
    shapes.(i + 1) <- viewop_output_shape op shapes.(i)
  ) spec;
  shapes

(* --- pretty-printer --- *)

let pp_intlist fmt l =
  Format.pp_print_list ~pp_sep:(fun fmt () -> Format.fprintf fmt ",")
    Format.pp_print_int fmt l

let pp_viewop fmt = function
  | Vtranspose p ->
    Format.fprintf fmt "T(%a)" pp_intlist (Array.to_list p)
  | Vslice r ->
    Format.fprintf fmt "S(%a)"
      (Format.pp_print_list ~pp_sep:(fun fmt () -> Format.fprintf fmt ";")
         (fun fmt (start, stop, step) ->
            Format.fprintf fmt "%d:%d:%d" start stop step))
      (Array.to_list r)
  | Vbroadcast (a, s) -> Format.fprintf fmt "B(%d,%d)" a s
  | Vreshape s ->
    Format.fprintf fmt "R(%a)" pp_intlist (Array.to_list s)

let pp_viewspec fmt spec =
  Format.pp_print_list
    ~pp_sep:(fun fmt () -> Format.fprintf fmt ";")
    pp_viewop fmt spec

let pp_prim fmt = function
  | Neg -> Format.fprintf fmt "neg"
  | Exp -> Format.fprintf fmt "exp"
  | Log -> Format.fprintf fmt "log"
  | Logsigmoid -> Format.fprintf fmt "logsigmoid"
  | Sqrt -> Format.fprintf fmt "sqrt"
  | Relu -> Format.fprintf fmt "relu"
  | Step -> Format.fprintf fmt "step"
  | Erf -> Format.fprintf fmt "erf"
  | Erfinv -> Format.fprintf fmt "erfinv"
  | Add -> Format.fprintf fmt "add"
  | Sub -> Format.fprintf fmt "sub"
  | Mul -> Format.fprintf fmt "mul"
  | Div -> Format.fprintf fmt "div"
  | Max2 -> Format.fprintf fmt "max2"
  | Sum_axis a -> Format.fprintf fmt "sum_axis(%d)" a
  | Max_axis a -> Format.fprintf fmt "max_axis(%d)" a
  | Gather (axis, indices) ->
    Format.fprintf fmt "gather(%d,[%a])" axis
      (Format.pp_print_list ~pp_sep:(fun fmt () -> Format.fprintf fmt ",")
         Format.pp_print_int)
      (Array.to_list indices)
  | Argmax_axis a -> Format.fprintf fmt "argmax_axis(%d)" a
  | Select_axis a -> Format.fprintf fmt "select_axis(%d)" a
  | Scatter_add (axis, _, target_shape) ->
    Format.fprintf fmt "scatter_add(%d,target=[%a])" axis
      (Format.pp_print_list ~pp_sep:(fun fmt () -> Format.fprintf fmt ",")
         Format.pp_print_int)
      (Array.to_list target_shape)
  | Scatter_select_add (axis, sz) ->
    Format.fprintf fmt "scatter_select_add(%d,%d)" axis sz
  | Apply_view spec ->
    Format.fprintf fmt "apply_view(%a)" pp_viewspec spec
  | Adjoint_view (spec, shape) ->
    Format.fprintf fmt "adjoint_view(%a,[%a])" pp_viewspec spec
      pp_intlist (Array.to_list shape)
  | Matmul -> Format.fprintf fmt "matmul"

let rec pp_dist fmt = function
  | D_uniform -> Format.fprintf fmt "Uniform"
  | D_categorical w -> Format.fprintf fmt "Cat(%a)" pp w
  | D_pushforward { fwd_var; fwd; inv_var; inv; base } ->
    Format.fprintf fmt "Push(%s->%a, %s->%a, %a)"
      fwd_var pp fwd inv_var pp inv pp_dist base
  | D_product (a, b) ->
    Format.fprintf fmt "(%a × %a)" pp_dist a pp_dist b

and pp fmt = function
  | Const (_, v) ->
    Format.fprintf fmt "(const %a)" View.Ndview.pp v.View.Tensor.view
  | Var (_, s) -> Format.fprintf fmt "%s" s
  | Prim (_, p, args) ->
    Format.fprintf fmt "(%a %a)" pp_prim p
      (Format.pp_print_list ~pp_sep:Format.pp_print_space pp) args
  | Let (_, s, e, body) ->
    Format.fprintf fmt "(let %s = %a in@;<1 2>%a)" s pp e pp body
  | Rank (_, k, p, args) ->
    Format.fprintf fmt "(%a⎉%d %a)" pp_prim p k
      (Format.pp_print_list ~pp_sep:Format.pp_print_space pp) args
  | Sample (_, name, frame, dist) ->
    Format.fprintf fmt "(sample %s [%a] %a)" name
      pp_intlist (Array.to_list frame) pp_dist dist
  | Score (_, e) ->
    Format.fprintf fmt "(score %a)" pp e

(* --- site duplication check --- *)

exception Duplicate_site of loc * string

let check_sites expr =
  let seen = Hashtbl.create 8 in
  let rec walk = function
    | Sample (l, name, _, dist) ->
      if Hashtbl.mem seen name then raise (Duplicate_site (l, name));
      Hashtbl.replace seen name ();
      walk_dist dist
    | Score (_, e) -> walk e
    | Const _ | Var _ -> ()
    | Prim (_, _, args) -> List.iter walk args
    | Let (_, _, e, body) -> walk e; walk body
    | Rank (_, _, _, args) -> List.iter walk args
  and walk_dist = function
    | D_uniform -> ()
    | D_categorical e -> walk e
    | D_pushforward { fwd; inv; base; _ } -> walk fwd; walk inv; walk_dist base
    | D_product (a, b) -> walk_dist a; walk_dist b
  in
  walk expr
